HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.history
setopt inc_append_history
setopt share_history
setopt hist_ignore_dups

PS1="%(?.🤓.🥺) %F{cyan}%~ $%f "

if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi