#!/bin/sh
# Install all dotfiles into the home directory

set -ex

DOTFILESDIR=~/dotfiles/dotfiles

if [ -d $DOTFILESDIR ]; then
    for i in $DOTFILESDIR/*; do
        echo "Installing $(basename $i)..."
        if [ -f ~/.$(basename $i) ]; then
            echo "Removing existing file ~/.$(basename $i)"
            rm -rf ~/.$(basename $i)
        fi
        ln -s $i ~/.$(basename $i)
    done
fi